name: Crates
description: A dead simple and secure crates system.
main: com.firestartermc.crates.Crates
author: Firestarter Minecraft Servers
website: https://firestartermc.com
version: 2.0
api-version: 1.17

depend:
  - Kerosene